// Display-only labels. Source category keys, hashes, thumbnails and saved IDs stay unchanged.
const CATEGORY_DISPLAY_NAMES: Readonly<Record<string, string>> = {
  'pack_01::1. Portrait And Studio': 'Portrait & studio',
  'pack_01::2. Lighting Techniques': 'Light studies',
  'pack_01::3. Film And Analog Process': 'Film response',
  'pack_01::4. Documentary And Street': 'Documentary & camera',
  'pack_01::5. Commercial And Product': 'Commercial imaging',
  'pack_01::6. Nature And Wildlife': 'Nature imaging',
  'pack_01::7. Technical And Specialist Imaging': 'Technical capture',
  'pack_02::1. Film Genres': 'Cinema languages',
  'pack_02::2. TV And Broadcast': 'Broadcast formats',
  'pack_02::3. Animation Styles': 'Animation craft',
  'pack_02::4. Photography Eras': 'Historic photo processes',
  'pack_02::5. Lighting And Atmosphere': 'Cinematic lighting',
  'pack_02::6. Ink and Print Caricature': 'Ink & print caricature',
  'pack_02::11. Gag Strip Cartoons': 'Gag strip cartoons',
  'pack_02::12. Screen Cartoon Frames': 'Screen cartoon frames',
  'pack_02::13. Handmade Caricature Craft': 'Handmade caricature',
  'pack_02::7. Sensor And Technical Imaging': 'Sensor looks',
  'pack_02::8. Hand-Drawn And DIY Media': 'DIY drawing surfaces',
  'pack_02::9. Stop-Motion & Puppet Animation': 'Stop-motion & puppets',
  'pack_02::10. Animation Production Artifacts': 'Animation production',
  'pack_03::1. Render Engines': 'CGI rendering',
  'pack_03::2. Materials': 'CGI material response',
  'pack_03::3. Lighting And Atmosphere': 'CGI light',
  'pack_03::4. 3D Styles': 'Stylized 3D',
  'pack_03::5. Hard Surface And Product CGI': 'Hard-surface production',
  'pack_03::6. Organic Character And Bio CGI': 'Organic CGI',
  'pack_03::7. Environment And Worldbuilding': 'Environment directions',
  'pack_03::8. Sensor And Technical Shaders': 'Technical shaders',
  'pack_04::1. Comic Book Styles': 'Comics',
  "pack_04::2. Children's Illustration": 'Storybook illustration',
  'pack_04::3. Editorial And Poster': 'Editorial & posters',
  'pack_04::4. Painted Concept Frames': 'Painted concept frames',
  'pack_04::7. Search and Planning Studies': 'Search & planning',
  'pack_04::8. Object Design Drawings': 'Object design drawings',
  'pack_04::9. World Sheets and Kits': 'World sheets & kits',
  'pack_04::5. Ink And Print': 'Ink & print',
  'pack_04::6. Technical And Reference Sheets': 'Reference layouts',
  'pack_05::1. Modern Shonen & Action': 'Action drawing',
  'pack_05::2. Mecha & Cyberpunk': 'Mechanical anime',
  'pack_05::3. Isekai & High Fantasy': 'Fantasy anime',
  'pack_05::4. Dark Fantasy & Seinen': 'Dark anime',
  'pack_05::5. Action Motion Setpieces': 'Action staging',
  'pack_06::1. Traditional Painting': 'Painting',
  'pack_06::2. Drawing & Sketching': 'Drawing',
  'pack_06::3. Printmaking': 'Printmaking',
  'pack_06::4. Digital Art': 'Digital media',
  'pack_06::5. Mixed Media': 'Mixed media',
  'pack_06::6. Retro Game Visual Systems': 'Pixel constraints',
  'pack_06::7. Game Art Directions & UI': 'Game art & interfaces',
  'pack_07::1. Interior Design Systems': 'Interior systems',
  'pack_07::2. Architectural Movements And Vernaculars': 'Architectural systems',
  'pack_07::3. Civic Infrastructure And Specialty Spaces': 'Specialty spaces',
  'pack_07::4. Landscape And Garden Systems': 'Garden systems',
  'pack_07::5. Fantasy And Mythic Architecture': 'Imagined architecture',
  'pack_07::6. Toy Craft And Miniature Architecture': 'Miniature construction',
  'pack_07::7. Megastructure And Impossible Space': 'Impossible space',
  'pack_08::1. Contemporary Fashion': 'Contemporary clothing',
  'pack_08::2. Subcultures': 'Subcultural clothing',
  'pack_08::3. Historical & Fantasy': 'Historical clothing',
  'pack_08::4. Fantasy Sci-Fi Costume': 'Speculative costume',
  'pack_08::5. Fabric & Texture Focus': 'Fabric studies',
  'pack_09::1. Natural Materials': 'Natural surfaces',
  'pack_09::2. Man-Made Materials': 'Manufactured surfaces',
  'pack_09::3. Weathering And Decay': 'Wear & weathering',
  'pack_09::4. Tactile Surfaces': 'Tactile response',
  'pack_09::5. Elemental And FX': 'Elemental effects',
  'pack_10::1. Geometric Abstraction': 'Geometric abstraction',
  'pack_10::2. Fluid & Organic': 'Fluid abstraction',
  'pack_10::3. Digital Glitch & Noise': 'Digital artifacts',
  'pack_10::4. Surrealism & Dream': 'Surreal systems',
  'pack_10::5. Textile & Ornamental Patterns': 'Pattern systems',
  'pack_10::6. Material Surface Textures': 'Surface transformations',
  'pack_10::7. Diagram And Data Systems': 'Diagram languages',
  'pack_10::8. Point, Mosaic And Glass Systems': 'Unit-based illustration',
  'pack_10::9. Print And Light Finishes': 'Print & light finish',
  'pack_11::1. Toys And Crafts': 'Craft & miniatures',
  'pack_11::2. Artistic Mediums': 'Specialist illustration',
  'pack_11::3. Aesthetics': 'Digital aesthetics',
  'pack_11::4. Food And Drink': 'Food imagery',
  'pack_11::5. Micro Macro': 'Scale & microscopy',
  'pack_11::6. Sensor And Technical Imaging': 'Technical imaging',
  'pack_11::7. Diagram And Technical Drawing': 'Blueprint drawing',
  'pack_12::1. Neon Urban & Night Ops': 'Urban game capture',
  'pack_12::2. Arcane Temples & Mythic Realms': 'Mythic game capture',
  'pack_12::3. Sci-Fi Frontiers & Mech Zones': 'Sci-fi game capture',
  'pack_12::4. Sieges, Warfronts & Last Stands': 'Tactical game capture',
  'pack_12::5. Speed, Sport & Competitive Arenas': 'Speed & arena capture',
  'pack_12::6. Wilderness Hunts & Harsh Frontiers': 'Frontier game capture',
  'pack_12::7. Heists, Horror & Underworld Runs': 'Stealth & horror capture',
  'pack_12::8. Puzzle Chambers & Adventure Setpieces': 'Adventure game capture',
  'pack_13::1. Core Anime': 'Cel fundamentals',
  'pack_13::2. Slice Of Life, School And Music': 'Everyday anime',
  'pack_13::3. Shojo, Magical Girl & Visionary Classics': 'Expressive anime',
  'pack_13::4. Slice Of Life & Moe': 'Quiet character animation',
  'pack_13::5. Ink, Brush and Hatch': 'Ink & brush',
  'pack_13::6. Paint and Watercolor': 'Paint & watercolor',
  'pack_13::7. Flat Graphic Systems': 'Flat graphic systems',
  'pack_13::8. Cel Direction and Screen': 'Cel direction & screen',
  'pack_14::Demons, Yokai & Night Spirits': 'Night spirits',
  'pack_14::Tricksters & Shape-Shifters': 'Tricksters',
  'pack_14::Underworlds & Realms of the Dead': 'Underworlds',
  'pack_14::Sky, Sun & Storm Gods': 'Sky & storm',
  'pack_14::Sea Monsters & Water Spirits': 'Sea spirits',
  'pack_14::Beasts, Guardians & Chimeras': 'Beasts & guardians',
  'pack_14::Heroes & Epics': 'Heroes & epics',
  'pack_14::Creation, World Trees & Cosmos': 'Creation & cosmos',
  'pack_14::Witches, Oracles & Shamans': 'Oracles & witches',
  'pack_15::1. Classic Industrial Punks': 'Industrial futures',
  'pack_15::2. Neon, Net & Signal Punks': 'Signal futures',
  'pack_15::3. Eco, Repair & Climate Punks': 'Repair futures',
  'pack_15::4. Bio, Myco & Body Punks': 'Biological futures',
  'pack_15::5. Ocean, Ice & Terrain Punks': 'Terrain futures',
  'pack_15::6. Street, Riot & DIY Punks': 'DIY futures',
  'pack_15::7. Media, Vapor & Glitch Punks': 'Media futures',
  'pack_15::8. Occult, Myth & Gothic Punks': 'Occult futures',
  'pack_15::9. Space, Atomic & Ray Punks': 'Atomic & orbital futures',
  'pack_15::10. Primitive, Stone & Salvage Punks': 'Primitive & salvage futures',
  'pack_16::1. Limited Cel and Super Robot': 'Limited cel & super robot',
  'pack_16::10. Real Robot and Mechanical Cel': 'Real robot & machines',
  'pack_16::11. Character and City-Pop Cel': 'Character & city-pop cel',
  'pack_16::12. Painted Theatrical Cel': 'Painted theatrical cel',
  'pack_16::2. 90s Golden Era': 'Nineties cel craft',
  'pack_16::3. 2000s Classics': 'Early digital anime',
  'pack_16::4. Studio Masterpieces': 'Authored animation',
  'pack_16::5. Sports, Competition & Performance': 'Performance drawing',
  'pack_16::6. Samurai & Medieval': 'Period action',
  'pack_16::7. Horror': 'Horror animation',
  'pack_16::8. Manga Masters - Shonen & Battle': 'Manga masters: shonen and battle',
  'pack_16::9. Manga Masters - Seinen, Shojo & Gag': 'Manga masters: seinen, shojo and gag',
  'pack_17::1. Dark Fantasy & Gothic Courts': 'Matte dark fantasy',
  'pack_17::2. Dungeon Zine & Risograph Prints': 'Zine reproduction',
  'pack_17::3. Ink, Tarot & Bestiary Plates': 'Ink & plate formats',
  'pack_17::4. Rune-Tech & Apocalyptic Warfronts': 'Techno-fantasy design',
  'pack_17::5. Grimdark Game Systems & Tabletop': 'Game & tabletop formats',
  'pack_17::6. Dungeon Zine Assemblage & Stampwork': 'Dungeon zine assemblage',
  'pack_17::7. Pulp Fantasy Painting': 'Pulp fantasy painting',
  'pack_17::8. Medieval Fantasy Drawing Media': 'Fantasy drawing media',
  'pack_17::9. Gothic & Dungeon Art Directions': 'Gothic & dungeon art',
  'pack_17::10. Graphic & Feudal Art Directions': 'Graphic & feudal art',
  'pack_17::11. Dark Fantasy Masters': 'Dark fantasy masters',
  'pack_17::12. OSR Dungeon Zine Illustrators': 'OSR dungeon zine illustrators',
  'pack_12::9. Gothic & Dungeon Gameplay': 'Gothic & dungeon gameplay',
  'pack_12::10. Graphic & Feudal Gameplay': 'Graphic & feudal gameplay',
  'pack_12::11. Psychological & Tactical Gameplay': 'Psychological & tactical gameplay',
  'pack_24::1. Psychological Horror Aesthetics': 'Psychological horror',
  'pack_24::2. Tactical & Solitary Frontiers': 'Tactical & solitary frontiers',
  'pack_25::1. Logo & Symbol Systems': 'Logo & symbol systems',
  'pack_25::2. Interface Icon Systems': 'Interface icons',
  'pack_25::3. App & Illustrative Icons': 'App & illustrative icons',
  'pack_25::4. UI & App Design': 'UI & app design',
  'pack_25::5. Game UI, HUDs & Screen Graphics': 'Game UI & HUDs',
  'pack_25::6. Industrial & Product Design': 'Industrial & product design',
  'pack_25::7. Packaging & Label Design': 'Packaging & labels',
  'pack_25::8. Mockups & Product Presentation': 'Mockups & presentation',
  'pack_25::9. Advertising & Campaign Design': 'Advertising & campaigns',
  'pack_25::10. Typography & Lettering': 'Typography & lettering',
  'pack_25::11. Editorial & Publication Design': 'Editorial & publication',
  'pack_25::12. Information & Technical Graphics': 'Information graphics',
  'pack_25::13. Surface & Textile Design': 'Surface & textile design',
  'pack_25::14. Apparel & Merchandise Graphics': 'Apparel & merch graphics',
  'pack_25::15. Environmental Graphics & Wayfinding': 'Wayfinding & environmental graphics',
  'pack_25::16. Motion Styleframes & Broadcast': 'Motion styleframes',
  'pack_26::1. Character Design': 'Character design',
  'pack_26::2. Movie Posters': 'Movie posters',
  'pack_26::3. Manga Covers': 'Manga covers',
  'pack_26::4. Book Covers': 'Book covers',
  'pack_26::5. Comic Covers': 'Comic covers',
  'pack_26::6. Album Covers - Jazz, Soul & Hip-Hop': 'Album covers: jazz, soul & hip-hop',
  'pack_26::7. Album Covers - Rock, Metal & Electronic': 'Album covers: rock, metal & electronic',
  'pack_26::8. Comic Artists - Pages & Panels': 'Comic artists: pages & panels',
  'pack_26::9. Western Animation - Studios & Directors': 'Western animation: studios & directors',
  'pack_26::10. Model Sheets & Turnarounds': 'Model sheets',
  'pack_27::1. Horror Cinema 70s': 'Horror cinema 70s',
  'pack_27::2. Horror Cinema 80s': 'Horror cinema 80s',
  'pack_27::3. Horror Cinema 90s': 'Horror cinema 90s',
  'pack_27::4. Video Games 80s': 'Video games 80s',
  'pack_27::5. Video Games 90s': 'Video games 90s',
  'pack_27::6. Video Games 2000s': 'Video games 2000s',
  'pack_27::7. Sci-Fi Cinema 50s & 60s': 'Sci-fi cinema 50s & 60s',
  'pack_27::8. Sci-Fi Cinema 70s & 80s': 'Sci-fi cinema 70s & 80s',
  'pack_27::9. Sci-Fi Cinema 90s': 'Sci-fi cinema 90s',
  'pack_27::10. Classic Noir & Western': 'Classic noir & western',
  'pack_27::11. Action Cinema 80s & 90s': 'Action cinema 80s & 90s',
  'pack_27::12. Video Games 2010s': 'Video games 2010s',
  'pack_27::13. Video Games 2020s': 'Video games 2020s',
  'pack_28::1. Premium Collectible Statues': 'Premium collectible statues',
  'pack_28::2. Toys & Miniatures': 'Toys & miniatures',
  'pack_28::3. Mecha Design Languages': 'Mecha design languages',
  'pack_28::4. Industrial Form Languages': 'Industrial form languages',
  'pack_19::1. Ink Structures': 'Ink Structures',
  'pack_20::1. Print Registers': 'Print Registers',
  'pack_21::1. Paper & Pigment': 'Paper & Pigment',
  'pack_22::1. Workshop Painting': 'Workshop Painting',
  'pack_22::2. Epic Digital Painting': 'Epic Digital Painting',
  'pack_22::3. Strange Ink & Paint': 'Strange Ink & Paint',
  'pack_22::4. Storybook & Animation': 'Storybook & Animation',
  'pack_22::5. Character & Readable Forms': 'Character & Readable Forms',
  'pack_22::6. Anime Illustration': 'Anime Illustration',
  'pack_22::7. Manga Ink & Impact': 'Manga Ink & Impact',
  'pack_22::8. Technical Illustration': 'Technical Illustration',
  'pack_22::9. Comic & Cartoon Illustration': 'Comic & Cartoon Illustration',
  'pack_22::10. Printmaking & Reproduction': 'Printmaking & Reproduction',
  'pack_22::11. Ornament & Symbolic Illustration': 'Ornament & Symbolic Illustration',
  'pack_22::12. Crafted Materials & Miniatures': 'Crafted Materials & Miniatures',
  'pack_22::13. Vintage Collectible Illustration': 'Vintage Collectible Illustration',
  'pack_22::14. Symbolic Graphic Illustration': 'Symbolic Graphic Illustration',
  'pack_22::15. Digital Rendering Methods': 'Digital Rendering Methods',
  'pack_23::1. Manuscript Visual Systems': 'Manuscript Visual Systems',
  'pack_23::2. Print & Engraving': 'Print & Engraving',
  'pack_23::3. Medieval Material Studies': 'Medieval Material Studies',
  'pack_23::4. Regional Manuscript Traditions': 'Regional Manuscript Traditions',
  'pack_23::5. Revival & Storybook Illustration': 'Revival & Storybook Illustration',
  'pack_23::6. Classic RPG Visual Studies': 'Classic RPG Visual Studies',
  'pack_23::7. Indexed Raster Language': 'Indexed Raster Language',
  'pack_23::8. Retro 3D Visual Studies': 'Retro 3D Visual Studies',
  'pack_23::9. Painted RPG & Tactics': 'Painted RPG & Tactics',
  'pack_23::10. Tabletop Illustration Studies': 'Tabletop Illustration Studies',
  'pack_23::11. Modern Visual Techniques': 'Modern Visual Techniques',
  'pack_23::12. Hybrid Visual Studies': 'Hybrid Visual Studies',
  'pack_29::1. Stitched Picture Surfaces': 'Stitched pictures',
  'pack_30::1. Ceramic and Glass Surfaces': 'Ceramic & glass',
  'pack_31::1. Habitat Paintings and Specimen Plates': 'Habitat & specimen plates',
  'pack_32::1. Painted and Stitched Local Traditions': 'Painted & stitched traditions',
};

export function getStyleCategoryDisplayName(packId: string, sourceCategory: string) {
  return CATEGORY_DISPLAY_NAMES[`${packId}::${sourceCategory}`] ?? sourceCategory;
}
