import type { StyleCollection, StyleCollectionFamily } from './styleCollectionTypes';

export const STYLE_COLLECTION_FAMILIES = [
  {
    id: 'personal',
    title: 'Personal',
    description: 'Local user styles and fast return paths.',
    order: 10,
  },
  {
    id: 'capture_reality',
    title: 'Photography',
    description: 'Camera, optics, lighting, analog processes, and technical imaging.',
    order: 20,
  },
  {
    id: 'screen_motion',
    title: 'Screen & Animation',
    description: 'Film, broadcast, animation, cartoons, anime, and manga.',
    order: 30,
  },
  {
    id: 'illustration_art_media',
    title: 'Illustration & Print',
    description: 'Comics, publishing, painting, drawing, printmaking, and digital art.',
    order: 40,
  },
  {
    id: 'design_assets_materials',
    title: '3D, Materials & Design',
    description: '3D render, surfaces, patterns, fashion, spaces, games, and UI.',
    order: 50,
  },
  {
    id: 'worlds_genres',
    title: 'World Directions',
    description: 'Mythic, fantasy, punk, symbolic, and genre-world visual systems.',
    order: 60,
  },
  {
    id: 'experimental_play',
    title: 'Experimental',
    description: 'Abstract systems, glitch, toys, craft, food, and scale play.',
    order: 70,
  },
] as const satisfies StyleCollectionFamily[];

export const STYLE_COLLECTIONS = [
  {
    id: 'psychological_frontier_aesthetics',
    title: 'Psychological & Frontier Aesthetics',
    familyId: 'worlds_genres',
    description:
      'Psychological horror, tactical brushwork and industrial solitude. Paired gameplay profiles live in Game Originals.',
    icon: 'layers',
    order: 6,
    sourcePackIds: ['pack_24'],
    entries: [{ id: 'psychological-frontier-pack', kind: 'pack', packId: 'pack_24' }],
    facets: { medium: ['illustration'], workflow: ['image', 'edit'] },
  },
  {
    id: 'tcg_visual_styles',
    title: 'Trading Card Illustration',
    familyId: 'illustration_art_media',
    description:
      'Portable illustration methods from the TCG atlas. Finishes, layouts and combinations are cataloged separately as pending components.',
    icon: 'layers',
    order: 4,
    sourcePackIds: ['pack_22'],
    entries: [{ id: 'tcg-visual-pack', kind: 'pack', packId: 'pack_22' }],
    facets: { medium: ['illustration'], workflow: ['image', 'edit'] },
  },
  {
    id: 'medieval_visual_styles',
    title: 'Medieval Visual Atlas',
    familyId: 'worlds_genres',
    description:
      'Medieval visual languages, workshop methods and historical references adapted for reusable styles.',
    icon: 'book',
    order: 4,
    sourcePackIds: ['pack_23'],
    entries: [{ id: 'medieval-visual-pack', kind: 'pack', packId: 'pack_23' }],
    facets: { medium: ['illustration'], workflow: ['image', 'edit'] },
  },
  {
    id: 'portable_visual_studies',
    title: 'Portable Studies',
    familyId: 'illustration_art_media',
    description:
      'Twelve authored ink, print and paper studies. Preview images and visual evaluation are pending.',
    icon: 'pen',
    order: 5,
    sourcePackIds: ['pack_19', 'pack_20', 'pack_21'],
    entries: [
      { id: 'portable-ink', kind: 'pack', packId: 'pack_19' },
      { id: 'portable-print', kind: 'pack', packId: 'pack_20' },
      { id: 'portable-paper', kind: 'pack', packId: 'pack_21' },
    ],
    facets: { medium: ['ink', 'print', 'paper'], workflow: ['image', 'edit'] },
  },
  {
    id: 'my_styles',
    title: 'My Styles',
    familyId: 'personal',
    description: 'Local user-authored styles.',
    icon: 'sparkles',
    order: 10,
    sourcePackIds: ['user_styles'],
    entries: [{ id: 'user-styles-pack', kind: 'pack', packId: 'user_styles' }],
    facets: { workflow: ['image', 'edit', 'style-card'] },
  },
  {
    id: 'favorites',
    title: 'Favorites',
    familyId: 'personal',
    description: 'Styles the user has saved for quick reuse.',
    icon: 'heart',
    order: 20,
    sourcePackIds: ['favorites'],
    entries: [{ id: 'favorites-pack', kind: 'pack', packId: 'favorites' }],
  },
  {
    id: 'recent',
    title: 'Recent',
    familyId: 'personal',
    description: 'Recently used styles.',
    icon: 'clock',
    order: 30,
    sourcePackIds: [],
    entries: [],
  },
  {
    id: 'photography_camera',
    title: 'Photography',
    familyId: 'capture_reality',
    description:
      'Real-world photographic language, portrait, documentary, product, and nature looks.',
    icon: 'camera',
    order: 10,
    sourcePackIds: ['pack_01'],
    entries: [
      {
        id: 'photo-portrait',
        kind: 'category',
        packId: 'pack_01',
        categoryName: '1. Portrait And Studio',
      },
      {
        id: 'photo-documentary',
        kind: 'category',
        packId: 'pack_01',
        categoryName: '4. Documentary And Street',
      },
      {
        id: 'photo-commercial',
        kind: 'category',
        packId: 'pack_01',
        categoryName: '5. Commercial And Product',
      },
      {
        id: 'photo-nature',
        kind: 'category',
        packId: 'pack_01',
        categoryName: '6. Nature And Wildlife',
      },
    ],
    facets: { medium: ['photography'], domain: ['portrait', 'documentary', 'product', 'nature'] },
  },
  {
    id: 'analog_film_process',
    title: 'Film & Analog',
    familyId: 'capture_reality',
    description: 'Film stocks, historical photo eras, darkroom processes, and camera artifacts.',
    icon: 'film',
    order: 20,
    sourcePackIds: ['pack_01', 'pack_02'],
    entries: [
      {
        id: 'photo-film-process',
        kind: 'category',
        packId: 'pack_01',
        categoryName: '3. Film And Analog Process',
      },
      {
        id: 'pack02-photo-eras',
        kind: 'category',
        packId: 'pack_02',
        categoryName: '4. Photography Eras',
      },
    ],
    facets: {
      medium: ['photography', 'film'],
      era: ['analog', 'early-digital'],
      technique: ['process'],
    },
  },
  {
    id: 'lighting_optics_atmosphere',
    title: 'Light & Optics',
    familyId: 'capture_reality',
    description: 'Lighting setups, optical effects, atmosphere, and camera-adjacent techniques.',
    icon: 'bolt',
    order: 30,
    sourcePackIds: ['pack_01', 'pack_02', 'pack_03', 'pack_10'],
    entries: [
      {
        id: 'photo-lighting',
        kind: 'category',
        packId: 'pack_01',
        categoryName: '2. Lighting Techniques',
        displayCategory: 'Lighting Techniques',
        facetOverrides: { medium: ['photography'], technique: ['lighting'] },
      },
      {
        id: 'media-lighting-atmosphere',
        kind: 'category',
        packId: 'pack_02',
        categoryName: '5. Lighting And Atmosphere',
        displayCategory: 'Lighting And Atmosphere',
        facetOverrides: {
          domain: ['cinema', 'broadcast'],
          technique: ['lighting', 'atmosphere'],
        },
      },
      {
        id: 'cgi-lighting-atmosphere',
        kind: 'category',
        packId: 'pack_03',
        categoryName: '3. Lighting And Atmosphere',
        displayCategory: 'CGI Lighting And Atmosphere',
        facetOverrides: { medium: ['3d', 'cgi'], technique: ['lighting', 'atmosphere'] },
        role: 'secondary',
      },
      {
        id: 'pack10-neon-light-lines',
        kind: 'preset',
        packId: 'pack_10',
        presetId: 'SP10-078',
        displayCategory: 'Light Line Systems',
        role: 'cross_link',
        facetOverrides: { technique: ['neon', 'light'] },
      },
    ],
    facets: { technique: ['lighting', 'optics', 'atmosphere'] },
  },
  {
    id: 'technical_imaging',
    title: 'Technical Imaging',
    familyId: 'capture_reality',
    description:
      'Specialist imaging, surveillance looks, x-ray, thermal, micro, and macro scale views.',
    icon: 'scan',
    order: 40,
    sourcePackIds: ['pack_01', 'pack_02', 'pack_03', 'pack_11'],
    featuredPresetIds: ['SP01-028', 'SP01-029', 'SP02-058', 'SP03-043', 'SP11-034'],
    entries: [
      {
        id: 'photo-technical',
        kind: 'category',
        packId: 'pack_01',
        categoryName: '7. Technical And Specialist Imaging',
      },
      {
        id: 'pack02-sensor-technical',
        kind: 'category',
        packId: 'pack_02',
        categoryName: '7. Sensor And Technical Imaging',
        displayCategory: 'Sensor And Technical Imaging',
        facetOverrides: { domain: ['scientific', 'surveillance'], technique: ['sensor-imaging'] },
      },
      {
        id: 'cgi-sensor-technical',
        kind: 'category',
        packId: 'pack_03',
        categoryName: '8. Sensor And Technical Shaders',
        displayCategory: 'CGI Sensor And Technical Shaders',
        facetOverrides: { medium: ['3d', 'cgi'], technique: ['sensor-imaging'] },
        role: 'cross_link',
      },
      {
        id: 'pack11-sensor-technical',
        kind: 'category',
        packId: 'pack_11',
        categoryName: '6. Sensor And Technical Imaging',
        displayCategory: 'Sensor And Technical Imaging',
        facetOverrides: { domain: ['scientific', 'surveillance'], technique: ['sensor-imaging'] },
      },
      {
        id: 'scale-micro-macro',
        kind: 'category',
        packId: 'pack_11',
        categoryName: '5. Micro Macro',
        role: 'secondary',
      },
    ],
    facets: { domain: ['scientific', 'surveillance'], technique: ['technical-imaging', 'scale'] },
  },
  {
    id: 'cinema_film_genres',
    title: 'Cinema',
    familyId: 'screen_motion',
    description: 'Film genre grammar, cinematic staging, and feature-film looks.',
    icon: 'clapperboard',
    order: 10,
    sourcePackIds: ['pack_02', 'pack_27'],
    entries: [
      { id: 'film-genres', kind: 'category', packId: 'pack_02', categoryName: '1. Film Genres' },
      {
        id: 'pack27-horror-70s',
        kind: 'category',
        packId: 'pack_27',
        categoryName: '1. Horror Cinema 70s',
        role: 'cross_link',
      },
      {
        id: 'pack27-horror-80s',
        kind: 'category',
        packId: 'pack_27',
        categoryName: '2. Horror Cinema 80s',
        role: 'cross_link',
      },
      {
        id: 'pack27-horror-90s',
        kind: 'category',
        packId: 'pack_27',
        categoryName: '3. Horror Cinema 90s',
        role: 'cross_link',
      },
      {
        id: 'pack27-scifi-50s-60s',
        kind: 'category',
        packId: 'pack_27',
        categoryName: '7. Sci-Fi Cinema 50s & 60s',
        role: 'cross_link',
      },
      {
        id: 'pack27-scifi-70s-80s',
        kind: 'category',
        packId: 'pack_27',
        categoryName: '8. Sci-Fi Cinema 70s & 80s',
        role: 'cross_link',
      },
      {
        id: 'pack27-scifi-90s',
        kind: 'category',
        packId: 'pack_27',
        categoryName: '9. Sci-Fi Cinema 90s',
        role: 'cross_link',
      },
      {
        id: 'pack27-noir-western',
        kind: 'category',
        packId: 'pack_27',
        categoryName: '10. Classic Noir & Western',
        role: 'cross_link',
      },
      {
        id: 'pack27-action-80s-90s',
        kind: 'category',
        packId: 'pack_27',
        categoryName: '11. Action Cinema 80s & 90s',
        role: 'cross_link',
      },
    ],
    facets: { domain: ['cinema'], workflow: ['image', 'edit'] },
  },
  {
    id: 'decade_screens',
    title: 'Decade Screens',
    familyId: 'screen_motion',
    description:
      'Horror, sci-fi, noir, western and action cinema by decade, and video games from the 80s to the 2020s, named after their films, games and makers.',
    icon: 'clapperboard',
    order: 15,
    sourcePackIds: ['pack_27'],
    entries: [{ id: 'decade-screens-pack', kind: 'pack', packId: 'pack_27' }],
    facets: { workflow: ['image', 'edit'] },
  },
  {
    id: 'collectibles_form_languages',
    title: 'Collectibles & Form Languages',
    familyId: 'design_assets_materials',
    description:
      'Premium statues, toys and miniatures, plus mecha and industrial design languages that restyle the form of any subject.',
    icon: 'box',
    order: 15,
    sourcePackIds: ['pack_28'],
    entries: [{ id: 'collectibles-form-languages-pack', kind: 'pack', packId: 'pack_28' }],
    facets: { workflow: ['image', 'edit'] },
  },
  {
    id: 'tv_broadcast_analog_video',
    title: 'Broadcast & Video',
    familyId: 'screen_motion',
    description: 'Television, broadcast graphics, home video, CCTV, and analog media packages.',
    icon: 'tv',
    order: 20,
    sourcePackIds: ['pack_02'],
    entries: [
      {
        id: 'tv-broadcast',
        kind: 'category',
        packId: 'pack_02',
        categoryName: '2. TV And Broadcast',
      },
    ],
    facets: { domain: ['broadcast', 'media'], technique: ['analog-video'] },
  },
  {
    id: 'animation_cartoons',
    title: 'Animation & Cartoon',
    familyId: 'screen_motion',
    description: 'Animation traditions, cartoon exaggeration, caricature, and graphic humor.',
    icon: 'play',
    order: 30,
    sourcePackIds: ['pack_02', 'pack_26'],
    entries: [
      {
        id: 'animation-styles',
        kind: 'category',
        packId: 'pack_02',
        categoryName: '3. Animation Styles',
        displayCategory: 'Animation Styles',
        facetOverrides: { medium: ['animation'], domain: ['screen'] },
      },
      {
        id: 'cartoon-caricature',
        kind: 'category',
        packId: 'pack_02',
        categoryName: '6. Caricature And Cartoon Styles',
        displayCategory: 'Caricature And Cartoon Styles',
        facetOverrides: { medium: ['cartoon'], domain: ['caricature', 'humor'] },
      },
      {
        id: 'pack02-stop-motion',
        kind: 'category',
        packId: 'pack_02',
        categoryName: '9. Stop-Motion & Puppet Animation',
      },
      {
        id: 'pack02-animation-production',
        kind: 'category',
        packId: 'pack_02',
        categoryName: '10. Animation Production Artifacts',
      },
      {
        id: 'pack26-western-animation',
        kind: 'category',
        packId: 'pack_26',
        categoryName: '9. Western Animation - Studios & Directors',
        role: 'cross_link',
      },
    ],
    facets: { medium: ['animation', 'cartoon'], domain: ['screen'] },
  },
  {
    id: 'anime_manga',
    title: 'Anime & Manga',
    familyId: 'screen_motion',
    description:
      'Anime action, characters, classics, manga-adjacent styles, and prestige subgenres.',
    icon: 'sparkles',
    order: 40,
    sourcePackIds: ['pack_05', 'pack_13', 'pack_16', 'pack_04', 'pack_02', 'pack_22', 'pack_26'],
    entries: [
      { id: 'anime-battle-worlds', kind: 'pack', packId: 'pack_05' },
      { id: 'anime-character-lifestyle', kind: 'pack', packId: 'pack_13' },
      { id: 'anime-classics-prestige', kind: 'pack', packId: 'pack_16' },
      {
        id: 'pack02-cyberpunk-anime',
        kind: 'preset',
        packId: 'pack_02',
        presetId: 'SP02-011',
        role: 'cross_link',
      },
      {
        id: 'manga-shonen',
        kind: 'preset',
        packId: 'pack_04',
        presetId: 'SP04-004',
        role: 'cross_link',
      },
      {
        id: 'manga-shojo',
        kind: 'preset',
        packId: 'pack_04',
        presetId: 'SP04-005',
        role: 'cross_link',
      },
      {
        id: 'pack22-anime-illustration',
        kind: 'category',
        packId: 'pack_22',
        categoryName: '6. Anime Illustration',
        role: 'cross_link',
      },
      {
        id: 'pack22-manga-ink',
        kind: 'category',
        packId: 'pack_22',
        categoryName: '7. Manga Ink & Impact',
        role: 'cross_link',
      },
      {
        id: 'pack26-manga-covers',
        kind: 'category',
        packId: 'pack_26',
        categoryName: '3. Manga Covers',
        role: 'cross_link',
      },
    ],
    facets: { medium: ['anime', 'manga'], world: ['anime'] },
  },
  {
    id: 'comics_sequential',
    title: 'Comics',
    familyId: 'illustration_art_media',
    description: 'Comic book language, panels, sequential marks, and graphic storytelling.',
    icon: 'book',
    order: 10,
    sourcePackIds: ['pack_04', 'pack_22', 'pack_26'],
    entries: [
      {
        id: 'comic-book-styles',
        kind: 'category',
        packId: 'pack_04',
        categoryName: '1. Comic Book Styles',
      },
      {
        id: 'pack22-comic-cartoon',
        kind: 'category',
        packId: 'pack_22',
        categoryName: '9. Comic & Cartoon Illustration',
        role: 'cross_link',
      },
      {
        id: 'pack26-comic-pages',
        kind: 'category',
        packId: 'pack_26',
        categoryName: '8. Comic Artists - Pages & Panels',
        role: 'cross_link',
      },
    ],
    facets: { medium: ['comics'], domain: ['publishing'] },
  },
  {
    id: 'illustration_publishing',
    title: 'Editorial Illustration',
    familyId: 'illustration_art_media',
    description: 'Children books, posters, editorial systems, and concept illustration.',
    icon: 'palette',
    order: 20,
    sourcePackIds: ['pack_04'],
    entries: [
      {
        id: 'childrens-illustration',
        kind: 'category',
        packId: 'pack_04',
        categoryName: "2. Children's Illustration",
      },
      {
        id: 'editorial-poster',
        kind: 'category',
        packId: 'pack_04',
        categoryName: '3. Editorial And Poster',
      },
      { id: 'concept-art', kind: 'category', packId: 'pack_04', categoryName: '4. Concept Art' },
    ],
    facets: { medium: ['illustration'], domain: ['publishing', 'concept-art'] },
  },
  {
    id: 'drawing_ink_print',
    title: 'Drawing & Print',
    familyId: 'illustration_art_media',
    description: 'Draftsmanship, ink, engraving, printmaking, and reproducible marks.',
    icon: 'pen',
    order: 30,
    sourcePackIds: ['pack_02', 'pack_04', 'pack_06', 'pack_10', 'pack_11', 'pack_22', 'pack_23'],
    featuredPresetIds: ['SP04-061', 'SP04-062', 'SP06-018', 'SP06-031', 'SP10-079'],
    entries: [
      {
        id: 'pack02-hand-drawn-diy-media',
        kind: 'category',
        packId: 'pack_02',
        categoryName: '8. Hand-Drawn And DIY Media',
        role: 'secondary',
      },
      {
        id: 'pack04-ink-print',
        kind: 'category',
        packId: 'pack_04',
        categoryName: '5. Ink And Print',
      },
      {
        id: 'pack06-drawing',
        kind: 'category',
        packId: 'pack_06',
        categoryName: '2. Drawing & Sketching',
      },
      {
        id: 'pack06-printmaking',
        kind: 'category',
        packId: 'pack_06',
        categoryName: '3. Printmaking',
      },
      {
        id: 'pack10-print-finishes',
        kind: 'preset',
        packId: 'pack_10',
        presetIds: ['SP10-079', 'SP10-080'],
        displayCategory: 'Foil And Letterpress Finishes',
        role: 'cross_link',
        facetOverrides: { medium: ['printmaking'], technique: ['finish'] },
      },
      {
        id: 'pack11-silkscreen-print',
        kind: 'preset',
        packId: 'pack_11',
        presetId: 'SP11-044',
        displayCategory: 'Silkscreen Print',
        role: 'cross_link',
        facetOverrides: { medium: ['printmaking'], technique: ['silkscreen'] },
      },
      {
        id: 'pack22-strange-ink',
        kind: 'category',
        packId: 'pack_22',
        categoryName: '3. Strange Ink & Paint',
        role: 'cross_link',
      },
      {
        id: 'pack22-printmaking',
        kind: 'category',
        packId: 'pack_22',
        categoryName: '10. Printmaking & Reproduction',
        role: 'cross_link',
      },
      {
        id: 'pack23-manuscripts',
        kind: 'category',
        packId: 'pack_23',
        categoryName: '1. Manuscript Visual Systems',
        role: 'cross_link',
      },
      {
        id: 'pack23-engraving',
        kind: 'category',
        packId: 'pack_23',
        categoryName: '2. Print & Engraving',
        role: 'cross_link',
      },
      {
        id: 'pack23-regional-manuscripts',
        kind: 'category',
        packId: 'pack_23',
        categoryName: '4. Regional Manuscript Traditions',
        role: 'cross_link',
      },
    ],
    facets: { medium: ['drawing', 'ink', 'printmaking'] },
  },
  {
    id: 'painting_traditional',
    title: 'Painting',
    familyId: 'illustration_art_media',
    description: 'Pigment, paint handling, traditional surfaces, and mixed media.',
    icon: 'brush',
    order: 40,
    sourcePackIds: ['pack_06', 'pack_11', 'pack_22', 'pack_31'],
    entries: [
      {
        id: 'traditional-painting',
        kind: 'category',
        packId: 'pack_06',
        categoryName: '1. Traditional Painting',
      },
      { id: 'mixed-media', kind: 'category', packId: 'pack_06', categoryName: '5. Mixed Media' },
      {
        id: 'artistic-mediums',
        kind: 'category',
        packId: 'pack_11',
        categoryName: '2. Artistic Mediums',
        role: 'secondary',
      },
      {
        id: 'pack22-workshop-painting',
        kind: 'category',
        packId: 'pack_22',
        categoryName: '1. Workshop Painting',
        role: 'cross_link',
      },
      {
        id: 'pack31-habitat-plates',
        kind: 'category',
        packId: 'pack_31',
        categoryName: '1. Habitat Paintings and Specimen Plates',
      },
    ],
    facets: { medium: ['painting', 'mixed-media'] },
  },
  {
    id: 'digital_concept_art',
    title: 'Digital Art',
    familyId: 'illustration_art_media',
    description: 'Digital painting, matte/concept art, vector languages, and production art.',
    icon: 'wand',
    order: 50,
    sourcePackIds: ['pack_06', 'pack_04', 'pack_22'],
    entries: [
      {
        id: 'pack06-digital-art',
        kind: 'category',
        packId: 'pack_06',
        categoryName: '4. Digital Art',
      },
      {
        id: 'pack04-concept-art-cross',
        kind: 'category',
        packId: 'pack_04',
        categoryName: '4. Concept Art',
        role: 'cross_link',
      },
      {
        id: 'pack22-epic-digital-painting',
        kind: 'category',
        packId: 'pack_22',
        categoryName: '2. Epic Digital Painting',
        role: 'cross_link',
      },
    ],
    facets: { medium: ['digital-art'], domain: ['concept-art'] },
  },
  {
    id: 'cgi_product_render',
    title: '3D Rendering',
    familyId: 'design_assets_materials',
    description: 'Render engines, CGI styles, hard-surface product visuals, and 3D asset looks.',
    icon: 'box',
    order: 10,
    sourcePackIds: ['pack_03', 'pack_22', 'pack_28'],
    entries: [
      { id: 'pack03-all', kind: 'pack', packId: 'pack_03' },
      {
        id: 'pack22-digital-rendering',
        kind: 'category',
        packId: 'pack_22',
        categoryName: '15. Digital Rendering Methods',
        role: 'cross_link',
      },
      {
        id: 'pack28-mecha-languages',
        kind: 'category',
        packId: 'pack_28',
        categoryName: '3. Mecha Design Languages',
        role: 'cross_link',
      },
      {
        id: 'pack28-industrial-form',
        kind: 'category',
        packId: 'pack_28',
        categoryName: '4. Industrial Form Languages',
        role: 'cross_link',
      },
    ],
    facets: { medium: ['3d', 'cgi'], domain: ['product', 'render'] },
  },
  {
    id: 'materials_textures_surfaces',
    title: 'Materials & Surfaces',
    familyId: 'design_assets_materials',
    description:
      'Natural and synthetic materials, tactile surfaces, fabrics, and texture workflows.',
    icon: 'layers',
    order: 20,
    sourcePackIds: ['pack_09', 'pack_10', 'pack_08', 'pack_03', 'pack_29', 'pack_30'],
    entries: [
      { id: 'pack09-materials', kind: 'pack', packId: 'pack_09' },
      {
        id: 'pack10-materials',
        kind: 'category',
        packId: 'pack_10',
        categoryName: '6. Material Surface Textures',
        role: 'secondary',
      },
      {
        id: 'pack08-fabrics',
        kind: 'category',
        packId: 'pack_08',
        categoryName: '5. Fabric & Texture Focus',
        role: 'secondary',
      },
      {
        id: 'pack03-materials',
        kind: 'category',
        packId: 'pack_03',
        categoryName: '2. Materials',
        role: 'cross_link',
      },
      {
        id: 'pack29-stitched-pictures',
        kind: 'category',
        packId: 'pack_29',
        categoryName: '1. Stitched Picture Surfaces',
      },
      {
        id: 'pack30-ceramic-glass',
        kind: 'category',
        packId: 'pack_30',
        categoryName: '1. Ceramic and Glass Surfaces',
      },
    ],
    facets: { medium: ['material', 'texture'], workflow: ['texture'] },
  },
  {
    id: 'patterns_ornament',
    title: 'Pattern & Ornament',
    familyId: 'design_assets_materials',
    description: 'Textile, ornamental, repeat, and decorative surface systems.',
    icon: 'grid',
    order: 30,
    sourcePackIds: ['pack_10', 'pack_22'],
    featuredPresetIds: ['SP10-070', 'SP10-075', 'SP10-072', 'SP10-073', 'SP10-074'],
    entries: [
      {
        id: 'patterns-ornament',
        kind: 'category',
        packId: 'pack_10',
        categoryName: '5. Textile & Ornamental Patterns',
      },
      {
        id: 'point-mosaic-glass',
        kind: 'category',
        packId: 'pack_10',
        categoryName: '8. Point, Mosaic And Glass Systems',
        role: 'secondary',
      },
      {
        id: 'pack22-ornament',
        kind: 'category',
        packId: 'pack_22',
        categoryName: '11. Ornament & Symbolic Illustration',
        role: 'cross_link',
      },
    ],
    facets: { medium: ['pattern', 'ornament'] },
  },
  {
    id: 'diagrams_blueprints_technical_sheets',
    title: 'Diagrams & Sheets',
    familyId: 'design_assets_materials',
    description:
      'Blueprints, callout sheets, wireframes, data diagrams, maps, and reference plates.',
    icon: 'grid',
    order: 35,
    sourcePackIds: ['pack_02', 'pack_04', 'pack_10', 'pack_11', 'pack_22'],
    featuredPresetIds: ['SP04-057', 'SP10-067', 'SP10-076', 'SP11-033', 'SP04-098'],
    entries: [
      {
        id: 'pack02-improvised-diagram-media',
        kind: 'preset',
        packId: 'pack_02',
        presetIds: ['SP02-091', 'SP02-098'],
        displayCategory: 'Improvised Diagram Media',
        role: 'cross_link',
        facetOverrides: { technique: ['diagram', 'sketch'] },
      },
      {
        id: 'pack04-technical-reference-sheets',
        kind: 'category',
        packId: 'pack_04',
        categoryName: '6. Technical And Reference Sheets',
      },
      {
        id: 'pack04-world-map-concept',
        kind: 'preset',
        packId: 'pack_04',
        presetId: 'SP04-098',
        displayCategory: 'Cartography And Spatial Maps',
        role: 'cross_link',
        facetOverrides: { technique: ['cartography'], domain: ['worldbuilding'] },
      },
      {
        id: 'pack10-diagram-data-systems',
        kind: 'category',
        packId: 'pack_10',
        categoryName: '7. Diagram And Data Systems',
        displayCategory: 'Diagram And Data Systems',
        role: 'cross_link',
        facetOverrides: { technique: ['diagram', 'blueprint', 'cartography', 'data'] },
      },
      {
        id: 'pack11-diagram-technical-drawing',
        kind: 'category',
        packId: 'pack_11',
        categoryName: '7. Diagram And Technical Drawing',
      },
      {
        id: 'pack22-technical-illustration',
        kind: 'category',
        packId: 'pack_22',
        categoryName: '8. Technical Illustration',
        role: 'cross_link',
      },
    ],
    facets: {
      medium: ['diagram', 'technical-drawing'],
      domain: ['interface', 'reference', 'blueprint'],
    },
  },
  {
    id: 'fashion_costume_wearables',
    title: 'Wardrobe Directions',
    familyId: 'design_assets_materials',
    description: 'Fashion systems, costumes, subcultures, textiles, and wearable identities.',
    icon: 'shirt',
    order: 40,
    sourcePackIds: ['pack_08'],
    entries: [{ id: 'pack08-all', kind: 'pack', packId: 'pack_08' }],
    facets: { domain: ['fashion', 'costume'] },
  },
  {
    id: 'architecture_interiors_places',
    title: 'Architecture & Interiors',
    familyId: 'design_assets_materials',
    description: 'Interior design, architecture, civic spaces, gardens, and spatial worldbuilding.',
    icon: 'building',
    order: 50,
    sourcePackIds: ['pack_01', 'pack_04', 'pack_07'],
    featuredPresetIds: ['SP07-001', 'SP07-017', 'SP07-041', 'SP01-056', 'SP04-091'],
    entries: [
      {
        id: 'photo-architecture-interiors',
        kind: 'preset',
        packId: 'pack_01',
        presetIds: ['SP01-056', 'SP01-057'],
        displayCategory: 'Architecture And Interior Photography',
        role: 'cross_link',
        facetOverrides: { medium: ['photography'], domain: ['architecture', 'interiors'] },
      },
      {
        id: 'pack04-architecture-massing-model',
        kind: 'preset',
        packId: 'pack_04',
        presetId: 'SP04-091',
        displayCategory: 'Architecture Concept Models',
        role: 'cross_link',
        facetOverrides: { medium: ['concept-art'], domain: ['architecture'] },
      },
      {
        id: 'pack07-interiors',
        kind: 'category',
        packId: 'pack_07',
        categoryName: '1. Interior Design Systems',
      },
      {
        id: 'pack07-architecture-movements',
        kind: 'category',
        packId: 'pack_07',
        categoryName: '2. Architectural Movements And Vernaculars',
      },
      {
        id: 'pack07-civic-spaces',
        kind: 'category',
        packId: 'pack_07',
        categoryName: '3. Civic Infrastructure And Specialty Spaces',
      },
      {
        id: 'pack07-landscape-gardens',
        kind: 'category',
        packId: 'pack_07',
        categoryName: '4. Landscape And Garden Systems',
      },
    ],
    facets: { domain: ['architecture', 'interiors', 'places'] },
  },
  {
    id: 'covers_posters_characters',
    title: 'Covers, Posters & Characters',
    familyId: 'illustration_art_media',
    description:
      'Character design languages plus movie posters and manga, book and comic covers, named after the artists, studios and eras that defined them.',
    icon: 'book',
    order: 15,
    sourcePackIds: ['pack_26'],
    entries: [{ id: 'covers-posters-characters-pack', kind: 'pack', packId: 'pack_26' }],
    facets: { workflow: ['image', 'edit'] },
  },
  {
    id: 'applied_design_systems',
    title: 'Applied Design',
    familyId: 'design_assets_materials',
    description:
      'Logos, icons, interfaces, products, packaging, type, editorial, data, textiles, merch, wayfinding and motion styleframes. Requested words, marks and data stay exact.',
    icon: 'layers',
    order: 55,
    sourcePackIds: ['pack_25'],
    entries: [{ id: 'applied-design-pack', kind: 'pack', packId: 'pack_25' }],
    facets: { workflow: ['image', 'edit'] },
  },
  {
    id: 'games_ui_worlds',
    title: 'Game Formats & UI',
    familyId: 'design_assets_materials',
    description:
      'Game worlds, UI systems, retro visuals, playable spaces, and sprite-adjacent styles.',
    icon: 'gamepad',
    order: 60,
    sourcePackIds: ['pack_12', 'pack_06', 'pack_23', 'pack_27'],
    entries: [
      { id: 'pack12-game-worlds', kind: 'pack', packId: 'pack_12' },
      {
        id: 'retro-game-visuals',
        kind: 'category',
        packId: 'pack_06',
        categoryName: '6. Retro Game Visual Systems',
      },
      {
        id: 'game-art-ui',
        kind: 'category',
        packId: 'pack_06',
        categoryName: '7. Game Art Directions & UI',
      },
      {
        id: 'pack23-classic-rpg',
        kind: 'category',
        packId: 'pack_23',
        categoryName: '6. Classic RPG Visual Studies',
        role: 'cross_link',
      },
      {
        id: 'pack23-indexed-raster',
        kind: 'category',
        packId: 'pack_23',
        categoryName: '7. Indexed Raster Language',
        role: 'cross_link',
      },
      {
        id: 'pack23-retro-3d',
        kind: 'category',
        packId: 'pack_23',
        categoryName: '8. Retro 3D Visual Studies',
        role: 'cross_link',
      },
      {
        id: 'pack23-painted-rpg',
        kind: 'category',
        packId: 'pack_23',
        categoryName: '9. Painted RPG & Tactics',
        role: 'cross_link',
      },
      {
        id: 'pack23-tabletop',
        kind: 'category',
        packId: 'pack_23',
        categoryName: '10. Tabletop Illustration Studies',
        role: 'cross_link',
      },
      {
        id: 'pack23-modern-visual',
        kind: 'category',
        packId: 'pack_23',
        categoryName: '11. Modern Visual Techniques',
        role: 'cross_link',
      },
      {
        id: 'pack23-hybrid-visual',
        kind: 'category',
        packId: 'pack_23',
        categoryName: '12. Hybrid Visual Studies',
        role: 'cross_link',
      },
      {
        id: 'pack27-games-80s',
        kind: 'category',
        packId: 'pack_27',
        categoryName: '4. Video Games 80s',
        role: 'cross_link',
      },
      {
        id: 'pack27-games-90s',
        kind: 'category',
        packId: 'pack_27',
        categoryName: '5. Video Games 90s',
        role: 'cross_link',
      },
      {
        id: 'pack27-games-2000s',
        kind: 'category',
        packId: 'pack_27',
        categoryName: '6. Video Games 2000s',
        role: 'cross_link',
      },
      {
        id: 'pack27-games-2010s',
        kind: 'category',
        packId: 'pack_27',
        categoryName: '12. Video Games 2010s',
        role: 'cross_link',
      },
      {
        id: 'pack27-games-2020s',
        kind: 'category',
        packId: 'pack_27',
        categoryName: '13. Video Games 2020s',
        role: 'cross_link',
      },
    ],
    facets: { domain: ['games', 'ui'], workflow: ['sprite'] },
  },
  {
    id: 'speculative_architecture_places',
    title: 'Speculative Spaces',
    familyId: 'worlds_genres',
    description:
      'Fantasy architecture, impossible space, megastructures, and spatial world systems.',
    icon: 'building',
    order: 5,
    sourcePackIds: ['pack_07'],
    featuredPresetIds: ['SP07-051', 'SP07-064', 'SP07-075', 'SP07-076', 'SP07-079'],
    entries: [
      {
        id: 'pack07-fantasy-architecture',
        kind: 'category',
        packId: 'pack_07',
        categoryName: '5. Fantasy And Mythic Architecture',
      },
      {
        id: 'pack07-megastructure-impossible-space',
        kind: 'category',
        packId: 'pack_07',
        categoryName: '7. Megastructure And Impossible Space',
      },
    ],
    facets: { world: ['fantasy', 'impossible-space'], domain: ['architecture'] },
  },
  {
    id: 'myth_folklore_ritual',
    title: 'Myth & Folklore',
    familyId: 'worlds_genres',
    description:
      'Myth-informed visual treatments built through symbolism, form, light, texture, and composition.',
    icon: 'moon',
    order: 10,
    sourcePackIds: ['pack_14'],
    entries: [{ id: 'pack14-mythic', kind: 'pack', packId: 'pack_14' }],
    facets: { world: ['myth', 'folklore', 'ritual'] },
  },
  {
    id: 'dungeon_dark_fantasy_wargame',
    title: 'Dark Fantasy',
    familyId: 'worlds_genres',
    description: 'Dungeon zines, dark fantasy, gothic wargame, bestiary, and inked fantasy plates.',
    icon: 'sword',
    order: 20,
    sourcePackIds: ['pack_17'],
    entries: [{ id: 'pack17-dungeon-fantasy', kind: 'pack', packId: 'pack_17' }],
    facets: { world: ['dungeon', 'dark-fantasy', 'wargame'] },
  },
  {
    id: 'punk_alt_futures',
    title: 'Alternate Futures',
    familyId: 'worlds_genres',
    description:
      'Punk futures, civic alt-tech, subcultures, climate futures, and speculative systems.',
    icon: 'zap',
    order: 30,
    sourcePackIds: ['pack_15', 'pack_11', 'pack_08'],
    entries: [
      { id: 'pack15-punk-spectrum', kind: 'pack', packId: 'pack_15' },
      {
        id: 'pack11-aesthetics',
        kind: 'category',
        packId: 'pack_11',
        categoryName: '3. Aesthetics',
        role: 'secondary',
      },
      {
        id: 'pack08-subcultures',
        kind: 'category',
        packId: 'pack_08',
        categoryName: '2. Subcultures',
        role: 'cross_link',
      },
    ],
    facets: { world: ['punk', 'future'], domain: ['subculture'] },
  },
  {
    id: 'surreal_dream_symbolic',
    title: 'Surreal Directions',
    familyId: 'worlds_genres',
    description: 'Surrealism, dream spaces, symbolism, liminal moods, and strange narrative logic.',
    icon: 'moon-stars',
    order: 40,
    sourcePackIds: ['pack_10'],
    entries: [
      {
        id: 'surreal-dream',
        kind: 'category',
        packId: 'pack_10',
        categoryName: '4. Surrealism & Dream',
      },
    ],
    facets: { world: ['surreal', 'symbolic', 'dream'] },
  },
  {
    id: 'abstract_glitch_systems',
    title: 'Abstract & Signal',
    familyId: 'experimental_play',
    description:
      'Geometric abstraction, glitch, digital noise, diagrams, and systemic visual languages.',
    icon: 'sliders',
    order: 10,
    sourcePackIds: ['pack_10'],
    entries: [
      {
        id: 'geometric-abstraction',
        kind: 'category',
        packId: 'pack_10',
        categoryName: '1. Geometric Abstraction',
      },
      {
        id: 'fluid-organic',
        kind: 'category',
        packId: 'pack_10',
        categoryName: '2. Fluid & Organic',
      },
      {
        id: 'digital-glitch-noise',
        kind: 'category',
        packId: 'pack_10',
        categoryName: '3. Digital Glitch & Noise',
      },
      {
        id: 'diagram-print-light',
        kind: 'category',
        packId: 'pack_10',
        categoryName: '7. Diagram And Data Systems',
      },
    ],
    facets: { medium: ['abstract', 'glitch'], technique: ['systems'] },
  },
  {
    id: 'toys_craft_food_scale',
    title: 'Craft, Food & Scale',
    familyId: 'experimental_play',
    description:
      'Toys, handmade craft, food looks, playful objects, and scale-shift visual systems.',
    icon: 'smile',
    order: 20,
    sourcePackIds: ['pack_11', 'pack_07', 'pack_28', 'pack_32'],
    featuredPresetIds: ['SP11-001', 'SP11-046', 'SP11-032', 'SP07-065', 'SP07-070'],
    entries: [
      {
        id: 'toys-crafts',
        kind: 'category',
        packId: 'pack_11',
        categoryName: '1. Toys And Crafts',
      },
      { id: 'food-drink', kind: 'category', packId: 'pack_11', categoryName: '4. Food And Drink' },
      {
        id: 'toy-miniature-architecture',
        kind: 'category',
        packId: 'pack_07',
        categoryName: '6. Toy Craft And Miniature Architecture',
        role: 'cross_link',
      },
      {
        id: 'pack28-statues',
        kind: 'category',
        packId: 'pack_28',
        categoryName: '1. Premium Collectible Statues',
        role: 'cross_link',
      },
      {
        id: 'pack28-toys',
        kind: 'category',
        packId: 'pack_28',
        categoryName: '2. Toys & Miniatures',
        role: 'cross_link',
      },
      {
        id: 'pack32-local-traditions',
        kind: 'category',
        packId: 'pack_32',
        categoryName: '1. Painted and Stitched Local Traditions',
      },
    ],
    facets: { medium: ['toy', 'craft', 'food'], technique: ['scale'] },
  },
] as const satisfies StyleCollection[];

export const STYLE_COLLECTIONS_BY_ID = new Map(STYLE_COLLECTIONS.map((item) => [item.id, item]));
